version: '3.3'

services:

  connect-distributed:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: connect-distributed
    ports:
      - 18083:8083
    volumes:
      - ./connect-output-file:/tmp
